### PR TITLE
74 toolbar trail tweaks

### PR DESCRIPTION
**Pull request by michaelsframe**
added visible "add" option to trail in toolbar, show error when added trail already exists, disable trail dropdown when no trails exist.

### CODE REVIEW

**Comment by bwhiteman** [comment]
Failing test. No option available. Video attached. For a user with no domain, the option is available. For a normal user, the option does not appear.
[addTrail.mp4.zip](https://github.com/Sotera/DatawakeDepot/files/82829/addTrail.mp4.zip)

**Comment by michaelsframe** [comment]
Video shows as corrupted, but I have seen this issue. Working on it

**Comment by bmcdougald** [comment]
I'm still seeing the behavior brandon describes above.

**Comment by bwhiteman** [comment]
@bmcdougald @michaelsframe, is this branch OBE?

**Comment by michaelsframe** [comment]
No, there is still a bug outstanding on it that you wrote. I’m working on it today

**Comment by michaelsframe** [comment]
updated to address 'Failing test. No option available. '

**Comment by bmcdougald** [comment]
Looks like the fixes all work.

**Pull request merged**
